[package]
name = "cf-poc"
version = "0.1.0"
edition = "2021"
authors = ["silvan <38138071+Sillyvan@users.noreply.github.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
http = "1"
worker = { version = "0.8", features = ["http"] }
worker-macros = { version = "0.8", features = ["http"] }
topcoat = { git = "https://github.com/tokio-rs/topcoat", rev = "3042dea0f9243ff1ea0c479a73a0d9da5c48ac3c", default-features = false, features = ["router"] }
